In [1]:
import numpy as np
import random
import scipy.stats as sps

C:\Dev\Jupyter\dist\pyenv3.7-win64\lib\site-packages\scipy\__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.5
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


### Перемножение матриц
Перемножим две квадратные матрицы двумя способами -- без использования пакета ***numpy*** и с ним.

In [13]:
# Для генерации матриц используем фукнцию random -- она используется для генерации случайных объектов 
# функция sample создает случайную выборку. В качестве аргумента ей передается кортеж (i,j),  
# здесь i -- число строк, j -- число столбцов.
a = np.random.sample((100, 100))
b = np.random.sample((100, 100))

# Выведим размерность (ранг) матрицы с помощью функции ndim.
# Используем функцию shape, для вывода

# ========
print(a.ndim)
print(a.shape)
# ========
print(a)
print(b)

2
(100, 100)
[[0.12121849 0.23469456 0.26268502 ... 0.33190098 0.7939254  0.87997532]
 [0.65399923 0.76793721 0.01836234 ... 0.85005813 0.27350749 0.70059743]
 [0.21135471 0.70206593 0.73909324 ... 0.90323355 0.4921536  0.95821535]
 ...
 [0.08634674 0.10057495 0.5103677  ... 0.26040784 0.83903423 0.74485684]
 [0.70576155 0.06055175 0.74211578 ... 0.13247875 0.44559979 0.81205805]
 [0.825095   0.02242683 0.78535816 ... 0.27347326 0.44696598 0.3995993 ]]
[[0.55369603 0.16246306 0.45920179 ... 0.27616664 0.48573838 0.62010838]
 [0.34206381 0.2100627  0.1607589  ... 0.6192264  0.32340655 0.17185165]
 [0.44060587 0.1397672  0.44548707 ... 0.52049174 0.64082995 0.75001792]
 ...
 [0.07135539 0.90922045 0.90501366 ... 0.43200199 0.36485905 0.6176016 ]
 [0.7331292  0.82016995 0.29878097 ... 0.84645926 0.92789215 0.01880676]
 [0.22476819 0.28105522 0.7943571  ... 0.64156812 0.26486477 0.73593345]]


In [6]:
def mult(first, second):
    """  
    first: list of "size" lists, each contains "size" floats --- первая матрица-аргумент
    second: list of "size" lists, each contains "size" floats --- вторая матрица-аргумент
    return c: list of "size" lists, each contains "size" floats --- матрица, являющаяся результатом умножения матриц a и b
    
    Функция принимает на вход две матрицы: first и second размерностью size x size
    Возвращает матрицу их произведения first * second = c 

    Реализуем умножение матриц без использования функций из пакета numpy
    """
    result = [[0 for i in range(len(second[0]))] for i in range(len(first))]
    for i in range(len(first)):
        for j in range(len(second[0])):
            for k in range(len(first[0])):
                result[i][j] += first[i][k] * second[k][j]
    return result

In [7]:
def np_mult(first, second):
    """  
    first: np.array[size, size]             --- первая матрица-аргумент
    second: np.array[size, size] --- вторая матрица-аргумент
    return c: np.array[size, size]       --- матрица, являющаяся результатом умножения матриц a и b
    
    Функция принимает на вход две матрицы: first и second размерностью size x size
    Возвращает матрицу их произведения first * second = c 

    Реализуем умножение матриц, используя функции из пакета numpy
    """
    result = first.dot(second)
    return result

In [8]:
%%time
# засечем время работы функции без NumPy
M1 = mult(a, b)

CPU times: total: 656 ms
Wall time: 655 ms


In [9]:
%%time
# засечем время работы функции с NumPy
M2 = np_mult(a, b)

CPU times: total: 0 ns
Wall time: 7.98 ms


In [10]:
# проверим корректность
assert np.allclose(np.array(M1), M2)

### Скалярное произведение векторов

Нам подаются на вход два вектора `a` и `b` в трехмерном пространстве. Заполним их случайными числами. Реализуем их скалярное произведение с помощью  `NumPy` и без. Засечем время работы

In [14]:
a = np.random.sample((1, 3))
a = list(a)[0]
b = np.random.sample((1, 3))
b = list(b)[0]
print(a, b)

[0.84684316 0.45184677 0.77859098] [0.27990072 0.59553563 0.69391718]


In [15]:
def scalar_product(v1, v2):
    """  
    v1: np.array[, n] --- первая матрица-аргумент длиной n
    v2: np.array[, n] --- вторая матрица-аргумент длиной n
    return c: float  --- результат скалярного произведения векторов v1 и v2

    Функция принимает на вход два вектора длиной n
    Возвращает число, равное их скалярному произведению v1 x v2 = c 

    Реализуим скалярное умножение векторов, не используя функции из пакета numpy

    """ 
    result = 0
    for i in range(len(v1)):
        result += v1[i]*v2[i]
    return result

In [16]:
def np_scalar_product(v1,v2):
    """  
    v1: np.array[, n] --- первая матрица-аргумент
    v2: np.array[, n] --- вторая матрица-аргумент
    return c: float  --- результат скалярного произведения векторов v1 и v2

    Функция принимает на вход два вектора длиной n
    Возвращает число, равное их скалярному произведению v1 x v2 = c 

    Реализуйте скалярное умножение векторов, используя функции из пакета numpy
    """ 
    result = np.dot(v1, v2)
    return result

In [17]:
%time product_1 = scalar_product(a,b)
%time product_2 = np_scalar_product(a,b)

# проверим корректность:
assert np.allclose(product_1, product_2)

CPU times: total: 0 ns
Wall time: 0 ns
CPU times: total: 0 ns
Wall time: 0 ns


Скорость вычислений вектоных и матричных операций в NumPy сильно превосходит скорость вычислений без него, по большей части потому, что функции numpy работаю с массивами данных одного типа (числовыми), это позволяет реализовать встроенные функции numpy на C/C++, что, конечно, делает numpy быстрее (функции, которые вызывает Numpy для работы с числовыми данными, сильно оптимизированы именно под эти задачи, а сам Python просто гоняет интерпретатор по циклу в таких операциях, что является чуть ли не самым большим замедлением в работе интерпретатора).

### Функция нахождения суммы четных диагональных элементов квадратной матрицы
Если таких элементов нет, то выведим `0`. Используем библиотеку Numpy

In [18]:
def np_diag_2k(a):
    """  
    a: np.array[m, m] --- первая матрица-аргумент
    return c: float   --- сумма элементов массива а, принадлежащих диагонали и являющимися четными

    Функция принимает на вход квадратную матрицу размерностью m x m и возвращает число,
    равное сумме четных диагональных элементов этой квадратной матрицы

    В реализации этой функции будем использовать функционал пакета numpy

    """ 
    result = 0
    diag = np.diagonal(a, offset=0, axis1=0, axis2=1)
    for i in range(len(diag)):
        if diag[i] % 2 == 0:
            result += diag[i]
            
    return result

In [19]:
# зададим некоторую квадратную матрицу
a = np.random.randint(1, 10, size=(5, 5))
a

array([[3, 4, 2, 6, 5],
       [7, 5, 1, 2, 6],
       [5, 1, 8, 1, 4],
       [6, 1, 2, 3, 1],
       [7, 2, 3, 3, 8]])

In [20]:
%%time
# засечем время работы функции с NumPy
np_diag_2k(a)

CPU times: total: 0 ns
Wall time: 7.98 ms


16

### Функция кумулятивной суммы
​
На вход дан двумерный массив $X$. Напишем функцию, которая для каждой строчки $(x = (x_1, x_2, \ldots, x_n)$ массива $X$ строит строчку $s = (s_1, s_2, \ldots, s_n)$,  где $s_k=x_1+...+x_k$, а затем выдаёт массив из построенных строчек. Используем библиотеку <code>numpy</code> (нам поможет функция <code>cumsum</code>). Выходом функции будет двумерный <code>numpy</code>-массив той же формы, что и $X$.
​ 

In [21]:
def cumsum(A):
    """  
    A: np.array[num_row, num_column]        --- матрица-аргумент
    return S: np.array[num_row, num_column] --- выходная матрица кумулятивных сумм

    Функция принимает на вход матрицу A размерностью n x m и возвращает 
    матрицу с той же размерностью n x m, i-ая строчка которой есть последовательность 
    кумулятивных сумм элементов i-ой строки матрицы A

    В реализации этой функции будем использовать функционал пакета numpy

    """ 
    result = np.cumsum(A, axis=-1)
    return result

In [24]:
# зададим некоторую последовательность и проверим ее на нашей функции. 
A = sps.uniform.rvs(size=10**3) 

%time S2 = cumsum(A)

CPU times: total: 0 ns
Wall time: 0 ns


### Преобразование и склеивание

​
Задан двумерный массив $X$. Для каждой строчки массива X сделаем следующее преобразование.

Пусть дана строчка x. Необходимо построить новый массив, где все элементы с нечетными индексами требуется заменить на число a (значение по умолчанию a=1). Все элементы с четными индексами нужно возвести в куб. Затем записать элементы в обратном порядке относительно их позиций. В конце требуется слить массив x с преобразованным x и вывести.

Напишем функцию, которая выполняет данное преобразование для каждой строчки двумерного массива X. Массив X при этом должен остаться без изменений.

Используем библиотеку numpy.

Пример:
$X = [[100,200,300,400,500]]$ -> $[[100,a,300,a,500]]$ -> $[[500^3,a,300^3,a,100^3]]$ -> склеиваем -> $[[100,200,300,400,500,500^3,a,300^3,a,100^3]]$

​

In [25]:
from copy import copy
def np_transformation(X, a=1):
    """  
    X: np.array[num_row, num_column]          --- матрица-аргумент
    a: float                                  --- значение для преобразования нечетных элементов строк в X
    return S: np.array[num_row, num_column*2] --- матрица, где строки являются 
    сконкатенированными строками изначальной матрицы X со строками, являющимися их преобразованиями

    Функция принимает на вход матрицу X размерностью n x m, число a и 
    возвращает  матрицу с размерностью n x m*2, i-ая строчка которой является склеенной
    i-ой строкой X с ее преобразованием ее строки transformation(X[i]), записанном в обратном порядке, 
    где преобразование для числа k определено как:
    transformation(k) = a if ind(k) % 2 == 0 else k**3

    В реализации этой функции будем использовать функционал пакета numpy

    """ 
    Y = np.copy(X)
    Y[:, 1::2] = a
    Y[:, 0::2] = Y[:, 0::2]**3
    Y[:, ::] = Y[:, ::-1]
    
    result = np.hstack((X, Y))
    
    return result

In [26]:
X = np.array([[i for i in range(1, 10, 2)]])
%time S2 = np_transformation(X, 5)

CPU times: total: 0 ns
Wall time: 0 ns


### Функция кодирования Run-length encoding
Напишем функцию для кодирование массива (Run-length encoding). Все подряд идущие повторения элементов функция сжимает в один элемент и считает количество повторений этого элемента. Функция возвращает кортеж из двух векторов одинаковой длины. Первый содержит элементы, а второй — сколько раз их нужно повторить. 

Пример: encode(np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])) = (np.array[1, 2, 3, 1, 5, 2, 3]), np.array[1, 2, 2, 2, 2, 1, 2])

In [27]:
def np_encode(a):
    """  
    a: np.array[, n] --- вектор-аргумент длиной n
    return (elems, repetitions): (np.array, np.array) --- выходной кортеж из вектора 
    элементов и вектора их количеств в подряд идущих повторениях

    Функция принимает на вход вектор a длиной n, добавляет в вектор elem сжатые 
    в один элемент подряд идущие повторения элементов входного вектора a, в вектор 
    repetitions добавляет длины последовательностей подряд идущих повторений. 
    Затем функция возвращает кортеж векторов (elems, repetitions).

    В реализации этой функции нбудем использовать функционал пакета numpy

    """ 
    # подготовим массив
    b = np.asanyarray(a)
    if b.ndim != 1:
        raise ValueError('only 1D array supported')
    n = b.shape[0]

    # обрабатывем пустой массив
    if n == 0:
        return np.array([]), np.array([])

    else:
        # ищем точку вхождения
        loc_run_start = np.empty(n, dtype=bool)
        loc_run_start[0] = True
        np.not_equal(b[:-1], b[1:], out=loc_run_start[1:])
        run_starts = np.nonzero(loc_run_start)[0]

        # ищем значение
        run_values = b[loc_run_start]

        # ищем длину значения
        run_lengths = np.diff(np.append(run_starts, n))

        return run_values, run_lengths

In [28]:
X = np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])

%time x, num = np_encode(X)

CPU times: total: 0 ns
Wall time: 997 µs
