In [1]:
import numpy as np
import random
import scipy.stats as sps

### Перемножение матриц
Перемножим две квадратные матрицы двумя способами -- без использования пакета ***numpy*** и с ним.

In [2]:
# Для генерации матриц используем фукнцию random -- она используется для генерации случайных объектов 
# функция sample создает случайную выборку. В качестве аргумента ей передается кортеж (i,j),  
# здесь i -- число строк, j -- число столбцов.
a = np.random.sample((100, 100))
b = np.random.sample((100, 100))

# Выведим размерность (ранг) матрицы с помощью функции ndim.
# Используем функцию shape, для вывода

# ========
print(a.ndim)
print(a.shape)
# ========
print(a)
print(b)

2
(100, 100)
[[0.92585663 0.85635057 0.24537459 ... 0.28976047 0.80949013 0.68667575]
 [0.7452127  0.74617535 0.83832959 ... 0.36830765 0.51462572 0.90522882]
 [0.720674   0.21569677 0.74242089 ... 0.82500171 0.12976939 0.87623172]
 ...
 [0.8517754  0.79487571 0.74421928 ... 0.03307149 0.78355453 0.66161074]
 [0.62248312 0.81396128 0.71424015 ... 0.94655858 0.70593978 0.84674759]
 [0.63302366 0.44232397 0.60099862 ... 0.69943703 0.5931907  0.18087657]]
[[0.36292663 0.84968114 0.70304779 ... 0.99789233 0.1994174  0.09557472]
 [0.99011361 0.99183434 0.70977227 ... 0.73899087 0.96223662 0.13323982]
 [0.68336026 0.31095586 0.32601356 ... 0.74326303 0.07894535 0.61064949]
 ...
 [0.41072221 0.92813187 0.00439812 ... 0.73950858 0.84175347 0.72435499]
 [0.55360672 0.49933647 0.73058057 ... 0.96866449 0.94800714 0.35390014]
 [0.19816292 0.90475132 0.21998013 ... 0.9406425  0.5405655  0.70759155]]


In [3]:
def mult(first, second):
    """  
    first: list of "size" lists, each contains "size" floats --- первая матрица-аргумент
    second: list of "size" lists, each contains "size" floats --- вторая матрица-аргумент
    return c: list of "size" lists, each contains "size" floats --- матрица, являющаяся результатом умножения матриц a и b
    
    Функция принимает на вход две матрицы: first и second размерностью size x size
    Возвращает матрицу их произведения first * second = c 

    Реализуем умножение матриц без использования функций из пакета numpy
    """
    result = [[0 for i in range(len(second[0]))] for i in range(len(first))]
    for i in range(len(first)):
        for j in range(len(second[0])):
            for k in range(len(first[0])):
                result[i][j] += first[i][k] * second[k][j]
    return result

In [4]:
def np_mult(first, second):
    """  
    first: np.array[size, size]             --- первая матрица-аргумент
    second: np.array[size, size] --- вторая матрица-аргумент
    return c: np.array[size, size]       --- матрица, являющаяся результатом умножения матриц a и b
    
    Функция принимает на вход две матрицы: first и second размерностью size x size
    Возвращает матрицу их произведения first * second = c 

    Реализуем умножение матриц, используя функции из пакета numpy
    """
    result = first.dot(second)
    return result

In [5]:
%%time
# засечем время работы функции без NumPy
M1 = mult(a, b)

CPU times: user 593 ms, sys: 1.05 ms, total: 594 ms
Wall time: 592 ms


In [6]:
%%time
# засечем время работы функции с NumPy
M2 = np_mult(a, b)

CPU times: user 1.13 ms, sys: 1 ms, total: 2.14 ms
Wall time: 1.21 ms


In [7]:
# проверим корректность
assert np.allclose(np.array(M1), M2)

### Скалярное произведение векторов

Нам подаются на вход два вектора `a` и `b` в трехмерном пространстве. Заполним их случайными числами. Реализуем их скалярное произведение с помощью  `NumPy` и без. Засечем время работы

In [8]:
a = np.random.sample((1, 3))
a = list(a)[0]
b = np.random.sample((1, 3))
b = list(b)[0]
print(a, b)

[0.00277387 0.92418064 0.22207715] [0.10966221 0.48238804 0.87585502]


In [9]:
def scalar_product(v1, v2):
    """  
    v1: np.array[, n] --- первая матрица-аргумент длиной n
    v2: np.array[, n] --- вторая матрица-аргумент длиной n
    return c: float  --- результат скалярного произведения векторов v1 и v2

    Функция принимает на вход два вектора длиной n
    Возвращает число, равное их скалярному произведению v1 x v2 = c 

    Реализуим скалярное умножение векторов, не используя функции из пакета numpy

    """ 
    result = 0
    for i in range(len(v1)):
        result += v1[i]*v2[i]
    return result

In [10]:
def np_scalar_product(v1,v2):
    """  
    v1: np.array[, n] --- первая матрица-аргумент
    v2: np.array[, n] --- вторая матрица-аргумент
    return c: float  --- результат скалярного произведения векторов v1 и v2

    Функция принимает на вход два вектора длиной n
    Возвращает число, равное их скалярному произведению v1 x v2 = c 

    Реализуйте скалярное умножение векторов, используя функции из пакета numpy
    """ 
    result = np.dot(v1, v2)
    return result

In [11]:
%time product_1 = scalar_product(a,b)
%time product_2 = np_scalar_product(a,b)

# проверим корректность:
assert np.allclose(product_1, product_2)

CPU times: user 36 μs, sys: 0 ns, total: 36 μs
Wall time: 49.4 μs
CPU times: user 59 μs, sys: 0 ns, total: 59 μs
Wall time: 72.7 μs


Скорость вычислений вектоных и матричных операций в NumPy сильно превосходит скорость вычислений без него, по большей части потому, что функции numpy работаю с массивами данных одного типа (числовыми), это позволяет реализовать встроенные функции numpy на C/C++, что, конечно, делает numpy быстрее (функции, которые вызывает Numpy для работы с числовыми данными, сильно оптимизированы именно под эти задачи, а сам Python просто гоняет интерпретатор по циклу в таких операциях, что является чуть ли не самым большим замедлением в работе интерпретатора).

### Функция нахождения суммы четных диагональных элементов квадратной матрицы
Если таких элементов нет, то выведим `0`. Используем библиотеку Numpy

In [12]:
def np_diag_2k(a):
    """  
    a: np.array[m, m] --- первая матрица-аргумент
    return c: float   --- сумма элементов массива а, принадлежащих диагонали и являющимися четными

    Функция принимает на вход квадратную матрицу размерностью m x m и возвращает число,
    равное сумме четных диагональных элементов этой квадратной матрицы

    В реализации этой функции будем использовать функционал пакета numpy

    """ 
    result = 0
    diag = np.diagonal(a, offset=0, axis1=0, axis2=1)
    for i in range(len(diag)):
        if diag[i] % 2 == 0:
            result += diag[i]
            
    return result

In [13]:
# зададим некоторую квадратную матрицу
a = np.random.randint(1, 10, size=(5, 5))
a

array([[1, 5, 6, 2, 6],
       [1, 1, 2, 7, 4],
       [3, 6, 3, 4, 1],
       [6, 7, 3, 6, 8],
       [7, 4, 3, 9, 9]])

In [14]:
%%time
# засечем время работы функции с NumPy
np_diag_2k(a)

CPU times: user 60 μs, sys: 2 μs, total: 62 μs
Wall time: 75.8 μs


np.int64(6)

### Функция кумулятивной суммы
​
На вход дан двумерный массив $X$. Напишем функцию, которая для каждой строчки $(x = (x_1, x_2, \ldots, x_n)$ массива $X$ строит строчку $s = (s_1, s_2, \ldots, s_n)$,  где $s_k=x_1+...+x_k$, а затем выдаёт массив из построенных строчек. Используем библиотеку <code>numpy</code> (нам поможет функция <code>cumsum</code>). Выходом функции будет двумерный <code>numpy</code>-массив той же формы, что и $X$.
​ 

In [15]:
def cumsum(A):
    """  
    A: np.array[num_row, num_column]        --- матрица-аргумент
    return S: np.array[num_row, num_column] --- выходная матрица кумулятивных сумм

    Функция принимает на вход матрицу A размерностью n x m и возвращает 
    матрицу с той же размерностью n x m, i-ая строчка которой есть последовательность 
    кумулятивных сумм элементов i-ой строки матрицы A

    В реализации этой функции будем использовать функционал пакета numpy

    """ 
    result = np.cumsum(A, axis=-1)
    return result

In [16]:
# зададим некоторую последовательность и проверим ее на нашей функции. 
A = sps.uniform.rvs(size=10**3) 

%time S2 = cumsum(A)

CPU times: user 77 μs, sys: 2 μs, total: 79 μs
Wall time: 93.7 μs


### Преобразование и склеивание

​
Задан двумерный массив $X$. Для каждой строчки массива X сделаем следующее преобразование.

Пусть дана строчка x. Необходимо построить новый массив, где все элементы с нечетными индексами требуется заменить на число a (значение по умолчанию a=1). Все элементы с четными индексами нужно возвести в куб. Затем записать элементы в обратном порядке относительно их позиций. В конце требуется слить массив x с преобразованным x и вывести.

Напишем функцию, которая выполняет данное преобразование для каждой строчки двумерного массива X. Массив X при этом должен остаться без изменений.

Используем библиотеку numpy.

Пример:
$X = [[100,200,300,400,500]]$ -> $[[100,a,300,a,500]]$ -> $[[500^3,a,300^3,a,100^3]]$ -> склеиваем -> $[[100,200,300,400,500,500^3,a,300^3,a,100^3]]$

​

In [17]:
from copy import copy
def np_transformation(X, a=1):
    """  
    X: np.array[num_row, num_column]          --- матрица-аргумент
    a: float                                  --- значение для преобразования нечетных элементов строк в X
    return S: np.array[num_row, num_column*2] --- матрица, где строки являются 
    сконкатенированными строками изначальной матрицы X со строками, являющимися их преобразованиями

    Функция принимает на вход матрицу X размерностью n x m, число a и 
    возвращает  матрицу с размерностью n x m*2, i-ая строчка которой является склеенной
    i-ой строкой X с ее преобразованием ее строки transformation(X[i]), записанном в обратном порядке, 
    где преобразование для числа k определено как:
    transformation(k) = a if ind(k) % 2 == 0 else k**3

    В реализации этой функции будем использовать функционал пакета numpy

    """ 
    Y = np.copy(X)
    Y[:, 1::2] = a
    Y[:, 0::2] = Y[:, 0::2]**3
    Y[:, ::] = Y[:, ::-1]
    
    result = np.hstack((X, Y))
    
    return result

In [18]:
X = np.array([[i for i in range(1, 10, 2)]])
%time S2 = np_transformation(X, 5)

CPU times: user 165 μs, sys: 0 ns, total: 165 μs
Wall time: 181 μs


### Функция кодирования Run-length encoding
Напишем функцию для кодирование массива (Run-length encoding). Все подряд идущие повторения элементов функция сжимает в один элемент и считает количество повторений этого элемента. Функция возвращает кортеж из двух векторов одинаковой длины. Первый содержит элементы, а второй — сколько раз их нужно повторить. 

Пример: encode(np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])) = (np.array[1, 2, 3, 1, 5, 2, 3]), np.array[1, 2, 2, 2, 2, 1, 2])

In [19]:
def np_encode(a):
    """  
    a: np.array[, n] --- вектор-аргумент длиной n
    return (elems, repetitions): (np.array, np.array) --- выходной кортеж из вектора 
    элементов и вектора их количеств в подряд идущих повторениях

    Функция принимает на вход вектор a длиной n, добавляет в вектор elem сжатые 
    в один элемент подряд идущие повторения элементов входного вектора a, в вектор 
    repetitions добавляет длины последовательностей подряд идущих повторений. 
    Затем функция возвращает кортеж векторов (elems, repetitions).

    В реализации этой функции нбудем использовать функционал пакета numpy

    """ 
    # подготовим массив
    b = np.asanyarray(a)
    if b.ndim != 1:
        raise ValueError('only 1D array supported')
    n = b.shape[0]

    # обрабатывем пустой массив
    if n == 0:
        return np.array([]), np.array([])

    else:
        # ищем точку вхождения
        loc_run_start = np.empty(n, dtype=bool)
        loc_run_start[0] = True
        np.not_equal(b[:-1], b[1:], out=loc_run_start[1:])
        run_starts = np.nonzero(loc_run_start)[0]

        # ищем значение
        run_values = b[loc_run_start]

        # ищем длину значения
        run_lengths = np.diff(np.append(run_starts, n))

        return run_values, run_lengths

In [20]:
X = np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])

%time x, num = np_encode(X)

CPU times: user 206 μs, sys: 0 ns, total: 206 μs
Wall time: 222 μs
